apiVersion: apps/v1
kind: Deployment

metadata:
  name: gui

spec:

  replicas: 1

  selector:
    matchLabels:
      app: gui

  template:

    metadata:
      labels:
        app: gui

    spec:

      containers:

      - name: gui

        image: 408502716092.dkr.ecr.ap-south-1.amazonaws.com/superkart-gui:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8501

---

apiVersion: v1
kind: Service

metadata:
  name: gui-service

  annotations:

    service.beta.kubernetes.io/aws-load-balancer-type: external

    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

spec:

  type: ClusterIP

  sessionAffinity: ClientIP

  selector:
    app: gui

  ports:

  - port: 80
    targetPort: 8501
